### ISSUE TITLE
Could you please tell me how to get the BKAI dataset

### ISSUE THREAD

**Issue by WangZhi-wz** [nikhilroxtomar/TGANet#4]
Could you please tell me how to get the BKAI dataset

**Comment by nikhilroxtomar** [comment]
Here is the link to the BKAI Polyp dataset: https://www.kaggle.com/c/bkai-igh-neopolyp

**Comment by tphankr** [comment]
Thank  you for you code. I saw the BKAI dataset has 3 classes. Can we use this dataset for you code because your code used for one class? If use 3 classes, where do we modify? Thanks.
![image](https://user-images.githubusercontent.com/37217354/224502528-2708c84e-4086-462d-ae95-26d5236e73ac.png)
